spring.application.name=FlowerStore2

spring.datasource.url=jdbc:mysql://localhost:3306/FlowerStore
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
